src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=CompteRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type_compte", type="string")
 * @ORM\DiscriminatorMap({
 *  "administrateur" = "Administrateur",
 *  "etudiant" = "Etudiant",
 *  "profTuteur" = "ProfTuteur",
 *  "maitreApprentissage" = "MaitreApprentissage"
 * })
 */

abstract class Compte implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $nomUtilisateur;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nomUtilisateur;
    }

    public function setNomUtilisateur(string $nomUtilisateur): self
    {
        $this->nomUtilisateur = $nomUtilisateur;

        return $this;
    }

    /**
     * @return string
     */
    public function getRoleName() : string {

            if ($this instanceof Administrateur) {
                return "Administrateur";
            }
            else if ($this instanceof Etudiant) {
                return "Étudiant";
            }
            else if ($this instanceof ProfTuteur) {
                return "Professeur";
            }
            else {
                return "Entreprise";
            }
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->nomUtilisateur;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFullName() : string {
        return $this->getNom() ." ". $this->getPrenom();
    }

}

templates/partials/displayCurrentMenu.html.twig
{% if app.request.attributes.get('_route') == route %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ path(route) }}">{{ tabName }}</a>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link" href="{{ path(route) }}">{{ tabName }}</a>
    </li>
{% endif %}

templates/partials/footer_js.html.twig
<script src="https://code.jquery.com/jquery-3.6.0.slim.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"></script>

templates/partials/jumbotron_texts_home.html.twig
<h1 class="display-4">{{ titre }}</h1>
<p class="lead">
    {{ contenu }}
</p>

templates/partials/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ path('home') }}">Gestion Livrets</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">

                {% include 'partials/displayCurrentMenu.html.twig' with {'route': "home", 'tabName': "Accueil"} %}

                {% if not app.user %}
                    {% include 'partials/displayCurrentMenu.html.twig' with {'route': "login", 'tabName': "Connexion"} %}
                {% endif %}

                {% if is_granted('ROLE_USER') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('livrets') }}">Livrets
                        </a>
                    </li>
                {% endif %}
            </ul>

            {% if app.user %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                            {{ app.user.nomUtilisateur }} ({{ app.user.roleName }})
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                            <a href="{{ path('logout') }}" class="dropdown-item">Deconnexion</a>
                        </div>
                    </li>
                </ul>
            {% endif %}

        </div>
    </nav>

{% for label,messages in app.flashes %}
    <div class="container">
        <div class="alert alert-{{ label }} mt-4">
            {% for message in messages %}
                <p>{{ message | raw }}</p>
            {% endfor %}
        </div>
    </div>
{% endfor %}