src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=CompteRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type_compte", type="string")
 * @ORM\DiscriminatorMap({
 *  "administrateur" = "Administrateur",
 *  "etudiant" = "Etudiant",
 *  "profTuteur" = "ProfTuteur",
 *  "maitreApprentissage" = "MaitreApprentissage"
 * })
 */

abstract class Compte implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $nomUtilisateur;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nomUtilisateur;
    }

    public function setNomUtilisateur(string $nomUtilisateur): self
    {
        $this->nomUtilisateur = $nomUtilisateur;

        return $this;
    }

    /**
     * @return string
     */
    public function getRoleName() : string {

            if ($this instanceof Administrateur) {
                return "Administrateur";
            }
            else if ($this instanceof Etudiant) {
                return "Étudiant";
            }
            else if ($this instanceof ProfTuteur) {
                return "Professeur";
            }
            else {
                return "Entreprise";
            }
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->nomUtilisateur;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFullName() : string {
        return $this->getNom() ." ". $this->getPrenom();
    }

}

src/Entity/Livret.php
<?php

namespace App\Entity;

use App\Repository\LivretRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivretRepository::class)
 */
class Livret
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomLivret;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class, inversedBy="livrets", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $formation;

    /**
     * @ORM\ManyToOne(targetEntity=etudiant::class, inversedBy="livrets", cascade={"persist"})
     * @ORM\JoinColumn (nullable=false)
     */
    private $etudiant;

    /**
     * @ORM\ManyToOne(targetEntity=MaitreApprentissage::class, inversedBy="livrets", cascade={"persist"})
     */
    private $maitreApprentissage;

    /**
     * @ORM\ManyToOne(targetEntity=ProfTuteur::class, inversedBy="livrets", cascade={"persist"})
     */
    private $profTuteur;

    /**
     * @ORM\ManyToOne(targetEntity=Periode::class, inversedBy="livrets", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $periode;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomLivret(): ?string
    {
        return $this->nomLivret;
    }

    public function setNomLivret(string $nomLivret): self
    {
        $this->nomLivret = $nomLivret;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getMaitreApprentissage(): ?MaitreApprentissage
    {
        return $this->maitreApprentissage;
    }

    public function setMaitreApprentissage(?MaitreApprentissage $maitreApprentissage): self
    {
        $this->maitreApprentissage = $maitreApprentissage;

        return $this;
    }

    public function getProfTuteur(): ?ProfTuteur
    {
        return $this->profTuteur;
    }

    public function setProfTuteur(?ProfTuteur $profTuteur): self
    {
        $this->profTuteur = $profTuteur;

        return $this;
    }

    public function getPeriode(): ?Periode
    {
        return $this->periode;
    }

    public function setPeriode(?Periode $periode): self
    {
        $this->periode = $periode;

        return $this;
    }

    public function getAllAccounts(): array
    {
        $accounts = array();
        $accounts[] = $this->etudiant;
        $accounts[] = $this->maitreApprentissage;
        $accounts[] = $this->profTuteur;

        return $accounts;
    }

    //Retourne true si l'utilisateur est concerné par ce livret
    public function isConcerned(Compte $compte):bool {
        if($compte == $this->etudiant || $compte == $this->maitreApprentissage || $compte == $this->profTuteur) {
            return true;
        }
        return false;
    }

}

src/Entity/Periode.php
<?php

namespace App\Entity;

use App\Repository\PeriodeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PeriodeRepository::class)
 */
class Periode
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $annee1;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $annee2;

    /**
     * @ORM\OneToMany(targetEntity=Livret::class, mappedBy="periode")
     */
    private $livrets;

    public function __construct()
    {
        $this->livrets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnnee1(): ?string
    {
        return $this->annee1;
    }

    public function setAnnee1(string $annee1): self
    {
        $this->annee1 = $annee1;

        return $this;
    }

    public function getAnnee2(): ?string
    {
        return $this->annee2;
    }

    public function setAnnee2(string $annee2): self
    {
        $this->annee2 = $annee2;

        return $this;
    }

    /**
     * @return Collection|Livret[]
     */
    public function getLivrets(): Collection
    {
        return $this->livrets;
    }

    public function addLivret(Livret $livret): self
    {
        if (!$this->livrets->contains($livret)) {
            $this->livrets[] = $livret;
            $livret->setPeriode($this);
        }

        return $this;
    }

    public function removeLivret(Livret $livret): self
    {
        if ($this->livrets->removeElement($livret)) {
            // set the owning side to null (unless already changed)
            if ($livret->getPeriode() === $this) {
                $livret->setPeriode(null);
            }
        }

        return $this;
    }

    public function getAnnees() : string {
        return $this->getAnnee1() . "-" . $this->getAnnee2();
    }
}

src/Controller/LivretsController.php
<?php

namespace App\Controller;

use App\Entity\Livret;
use App\Form\LivretFormType;
use App\Repository\LivretRepository;
use App\Service\LivretNamerService;
use App\Service\usernamePasswordMakerService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class LivretsController extends AbstractController
{
    /**
     * Permet d'afficher la liste des livrets en fonction du rôle
     *
     * @Route("/livrets", name="livrets")
     * @IsGranted("ROLE_USER")
     */
    public function index(Request $request, LivretRepository $repository, PaginatorInterface $paginator): Response
    {
        if($this->isGranted("ROLE_ADMIN")) {
            $donnees = $repository->findAll();

        }
        else {
            $donnees = $this->getUser()->getLivrets();
        }

        $livrets = $paginator->paginate(
            $donnees,$request->query->getInt('page',1),10
        );

        return $this->render('livrets/index.html.twig', [
            'livrets' => $livrets
         ]);
    }

    /**
     * Permet d'afficher la vue d'un livret
     *
     * @Route("/livrets/show/{id}", name="show_livret")
     * @Security("is_granted('ROLE_ADMIN') or livret.isConcerned(user)", message="Vous n'avez aucun lien avec ce livret, il est donc impossible pour vous de le consulter.")
     * @isGranted("ROLE_USER")
     * @param Livret $livret
     * @return Response
     */
    public function view(Livret $livret) {

        return $this->render('livrets/view.html.twig',[
            'livret' => $livret
        ]);
    }

    /**
     * Permet la suppression d'un livret
     *
     * @Route("/livrets/delete/{id}", name="delete_livret")
     * @Security("is_granted('ROLE_ADMIN') or user === livret.getEtudiant()", message="Ce livret ne vous appartient pas, vous ne pouvez pas le supprimer")
     * @param Livret $livret
     * @param EntityManagerInterface $manager
     */
    public function delete(Livret $livret, EntityManagerInterface $manager) {

        $name = $livret->getNomLivret();
        $manager->remove($livret);
        $manager->flush();

        $this->addFlash("success","Le livret<strong> " . $name . "</strong> a bien été supprimé !");

        return $this->redirectToRoute("livrets");

    }

    /**
     * @Route("/livrets/new", name="new_livret")
     * @isGranted("ROLE_ADMIN")
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function new(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder, usernamePasswordMakerService $usermaker, LivretNamerService $livretNamer) {

        $livret = new Livret();
        $form = $this->createForm(LivretFormType::class,$livret);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $usermaker->GenerateLivretUsersData($livret);
            $livretNamer->generateLivretName($livret);
            $manager->persist($livret);
            $manager->flush();
            $this->addFlash('success','Le livret a bien été enregistré avec succès !');
        }

        return $this->render('livrets/new.html.twig',[
            'form' => $form->createView()
        ]);

    }


}

templates/livrets/form_livret.html.twig
<div class="row">
    <div class="col-12">
        <div class="alert alert-light">
            <h2>{{ formTitle }}</h2>
            <hr>
            <div id="formSelect">
                {{ form_row(champSelect) }}
            </div>
            <h4><b>OU</b></h4>
            <div id="formAjout">
                {{ form_row(champNew) }}
            </div>

            {% if button is defined and button == true %}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Valider</button>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/livrets/index.html.twig
{% extends 'base_forms.html.twig' %}

{% block title %}Vos livrets{% endblock %}

{% block body %}

    <div class="container-fluid">
        <h1 class="my-3">
            {% if is_granted('ROLE_ADMIN') %}
                Tout les livrets
            {% else %}
                Mes livrets
            {% endif %}
        </h1>

        {% if livrets is empty %}
            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4 class="alert-heading">Aucun contenu!</h4>
                <p class="mb-0">Il n'y a pour l'instant aucun livrets renseignés ici !</p>
            </div>
        {% endif %}

        {% if is_granted("ROLE_ADMIN") %}
            <a href="{{ path('new_livret') }}" class="btn btn-primary btn-lg mb-3"><i class="fas fa-plus"></i>Ajouter un livret</a>
        {% endif %}

        <div class="table-responsive">
            <table class="table table-light">
                <thead>
                <tr>
                    <th scope="col">Intitulé</th>
                    <th scope="col">Période</th>
                    <th scope="col">Formation</th>
                    <th scope="col">Etudiant</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>

                {% for livret in livrets %}
                    <tr>
                        <td>{{ livret.nomLivret | raw }}</td>
                        <td>{{ livret.periode.annees }}</td>
                        <td>{{ livret.formation.libelle }}</td>
                        <td>{{ livret.etudiant.fullName }}</td>
                        <td>
                            <a href="{{ path('show_livret',{'id' : livret.id}) }}" class="btn btn-success"><i
                                        class="fas fa-eye"></i></a>
                            <a href="#" class="btn btn-info"><i
                                        class="fas fa-pen"></i></a>
                            {% if is_granted("ROLE_ADMIN") %}
                                <a href="{{ path('delete_livret', {'id' : livret.id}) }}" class="btn btn-danger"
                                   onclick="return confirm('Etes-vous sûr de vouloir supprimer ce livret ?');">
                                    <i class="fas fa-trash"></i>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        {{ knp_pagination_render(livrets,
            '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        ) }}
    </div>

{% endblock %}

templates/livrets/new.html.twig
{% extends 'base_forms.html.twig' %}

{% block title %}Nouveau livret{% endblock %}

{% block body %}
    <div class="container">

        <h1 class="my-5">Nouveau livret</h1>

        {{ form_start(form) }}

       {% include 'livrets/form_livret.html.twig' with {
            'formTitle': "Informations générales",
            'champSelect': form.periode,
            'champNew': form.nouvellePeriode,
        } %}

        {% include 'livrets/form_livret.html.twig' with {
            'formTitle': "Informations formation",
            'champSelect': form.formation,
            'champNew': form.nouvelleFormation,
        } %}

        {% include 'livrets/form_livret.html.twig' with {
            'formTitle': "Informations maître d'apprentissage",
            'champSelect': form.maitreApprentissage,
            'champNew': form.nouveauMaitreApprentissage,
        } %}

        {% include 'livrets/form_livret.html.twig' with {
            'formTitle': "Informations professeur tuteur",
            'champSelect': form.profTuteur,
            'champNew': form.nouveauProfTuteur,
        } %}

        {% include 'livrets/form_livret.html.twig' with {
            'formTitle': "Informations étudiant",
            'champSelect': form.etudiant,
            'champNew': form.nouveauEtudiant,
            'button': true
        } %}

    </div>
    {{ form_end(form) }}

{% endblock %}

{#
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/form_script.js') }}"></script>
{% endblock %}#}

templates/livrets/view.html.twig
{% extends 'base_forms.html.twig' %}

{% block title %}Consultation d'un livret{% endblock %}

{% block body %}
    {% set formation = livret.formation %}
    {% set etudiant = livret.etudiant %}

    <div class="container">
        <div class="alert alert-dismissible alert-info mt-3 h3">
            Informations sur le livret intitulé : {{ livret.nomLivret|raw }}
        </div>

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails du livret</h2>
                    <dl class="row">
                        <dt class="col-md-4">Période</dt>
                        <dd class="col-md-8 ">{{ livret.periode.annees }}</dd>
                        <dt class="col-md-4">Maître d'apprentissage</dt>
                        <dd class="col-md-8 ">{{ livret.maitreApprentissage.fullName }}</dd>
                        <dt class="col-md-4">Professeur tuteur</dt>
                        <dd class="col-md-8 ">{{ livret.profTuteur.fullName }}</dd>
                    </dl>
                    <hr>
                    <h2>Détails de l'étudiant</h2>
                    <dl class="row">
                        <dt class="col-md-4">Nom complet</dt>
                        <dd class="col-md-8 ">{{ etudiant.fullname }}</dd>
                        <dt class="col-md-4">Classe</dt>
                        <dd class="col-md-8 ">{{ etudiant.classe.nomClasse }}</dd>
                    </dl>
                    <hr>
                    <h2>Détails de la formation</h2>
                    <dl class="row">
                        <dt class="col-md-4">Intitulé</dt>
                        <dd class="col-md-8 ">{{ formation.libelle }}</dd>
                        <dt class="col-md-4">Nom de l'entreprise</dt>
                        <dd class="col-md-8 ">{{ livret.maitreApprentissage.entreprise.nom }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <a href="#" class="btn btn-primary btn-lg"><i class="fas fa-sticky-note"></i> Fiches de suivis</a>
    </div>

{% endblock %}